### ISSUE TITLE
Support dynamic form field

### ISSUE THREAD

**Issue by afc163** [react-component/form#100]
```jsx
this.state.switch ? getFiledDecorator('xxx')(
  <input />
) : getFiledDecorator('xxx')(
  <select />
)
```

https://github.com/ant-design/ant-design/issues/7302

**Comment by afc163** [comment]
Maybe we can try to resolve this problem elegantly.

**Comment by 330551887** [comment]
`{this.state.visible && <Modal visible={true} />}`

**Comment by benjycui** [comment]
这个问题，其实是因为共享同一个 fieldName 的多个组件类型不一样，所以在切换时，react 会先把之前的组件 unmount，然后就触发了这段逻辑

https://github.com/react-component/form/blob/f63c852b48801f07fe98e5d8f3bd99c4d326f5a6/src/createBaseForm.js#L308-L314

以上逻辑会把 field 相关的数据清除，并且，由于 React 调用 ref 的时机确定了被 unmount 的 ref(null) 会在 mount 的组件的 ref(component) 之后，所以数据是一定会被清除的。

![image](https://user-images.githubusercontent.com/3580607/32267765-5a862ca4-beba-11e7-9b07-f3da0c26a29d.png)

**Comment by benjycui** [comment]
rc-form 本来就需要在组件 unmount 时清理对应 field 的数据，而现在无法判断 developers 到底是想 unmount 一个 filed 还是仅仅是想替换，所以个人认为在 rc-form 里面是无法解决了，还是在业务代码里面处理吧。

```jsx
function NameField({ mode }) {
  return mode === 'select' ?
    <Select /> : <input />;
}

getFieldDecorator('name')(<NameField mode={mode} />)
```

**Comment by afc163** [comment]
- mount 的时候记录绑定过的 component 到一个数组，只有数组最后一个数组是生效的。
- unmount 的时候去清理数组相应的 component。

**Comment by benjycui** [comment]
这里的问题不在于 ref 引用不对，而是 rc-form 需要在组件 unmount 时清空对应的数据，ref(null) 其实和侵入组件 componentWillUnmount 效果是一样的。

所以现在的问题在于，B 的 componentWillMount 在 A 的 componentWillUnmount 之前，所以当 A 被 unmount 的时候，就把 B 的数据也清空了，而 rc-form 无法知道 A unmount 的原因是被替换还是 develoopers 不需要了。

**Comment by afc163** [comment]
didMount/didUpdate  push slice(-2)  willUnmount  unshift  读取 fieldMeta 和 ref 时以数组最后一个为准。
--

from @benjycui https://github.com/react-component/form/issues/116#issue-272476592
