### ISSUE TITLE
react-native 中取不到值，老是undefined

### ISSUE THREAD

**Issue by JavaBird** [react-component/form#101]
![image](https://user-images.githubusercontent.com/5122200/29918998-207601f8-8e7a-11e7-80a6-9ba1c8ea9ae6.png)
如图，
![image](https://user-images.githubusercontent.com/5122200/29919025-3edf956e-8e7a-11e7-96f1-04c1ca2c6bee.png)
愁死。

**Comment by benjycui** [comment]
麻烦提供可重现 repo 和具体步骤。

**Comment by benjycui** [comment]
Close for no response.

**Comment by Chincegen** [comment]
我现在RN项目也遇到了这个问题，一直获取不到值，undefined~
![image](https://user-images.githubusercontent.com/26915429/83093547-3a4e2e80-a0d2-11ea-8800-51a498b73a33.png)
