### ISSUE TITLE
mapPropsToFields 同步部分 fields 时，会导致其他 fields 值丢失

### ISSUE THREAD

**Issue by anianj** [react-component/form#104]
使用场景：
用户在表单里有一个 Select ，可以选择已有的条目，但是如果没有他想要的，这个 Select 旁边提供一个新增条目的 Button，点击 Button 后用户在一个弹出的Modal 里填入新增条目的信息，然后确定，会通过 saga 的 effect 把这条新增发送到服务端。
服务端新增完成后，会返回这条新增的id，我拿到这个id，回填到 redux state里，然后就需要通过 mapPropsToField 同步回 表单里，就出现了，mapPropsToField 只同步了这个id，而没有同步其他field，导致其他field 值丢失的情况。

riddle: 30617aaa

**Comment by afc163** [comment]
@benjycui 我还一直把这个当做 feature 来着。

**Comment by ladjzero** [comment]
https://github.com/react-component/form/commit/dda49b681c3a84f76accffdf98214303839edc71

这是个破坏性的升级！

如果我理解正确的话，reporter 的意思是 mapPropsToField 应该支持部分字段更新，不需要每次都 map 全量字段。

我认为每次 map 都是全量字段才是正确的，使用 mapPropsToField 即是 form 的 fieldsStore 由父组件来控制，应该表现得和受控的输入组件一样。

这个 commit 导致了我这边的一个 bug，当 mapPropsToField 将返回 {}，无法抹去 fieldsStore 上的字段信息。之前我利用这个 feature 来实现 reset 功能。

**Comment by afc163** [comment]
@benjycui

**Comment by anianj** [comment]
我觉得更好的方式是给mapPropsToFields 传一个额外的参数控制是否需要全量更新

**Comment by benjycui** [comment]
> 这个 commit 导致了我这边的一个 bug，当 mapPropsToField 将返回 {}，无法抹去 fieldsStore 上的字段信息。之前我利用这个 feature 来实现 reset 功能。

Reset 通过 resetFields 来实现才对？

**Comment by benjycui** [comment]
@anianj 考虑到 nested fields 的存在，我认为还是之前的行为是正确的，用 mapPropsToFields 的返回值替换之前的 fields，如果返回 `{}`，则清空fields。

将会在 rc-form@2.0 antd@3.0 里面把 mapPropsToFields 的行为回滚为之前的版本。

**Comment by ladjzero** [comment]
> Reset 通过 resetFields 来实现才对？

可以用 resetFields，我认为业务上的流程是 resetFields => onFieldsChange => DO CHANGE => mapPropsToFields

**Comment by benjycui** [comment]
rc-form@2.0.0 已经发布。

Try rc-form@2.0.0, and changelog https://github.com/react-component/form/blob/master/HISTORY.md#200--2017-11-07

If you meet any issue, feel free to file an issue, and I will try to fix it asap.

**Comment by VentionZong** [comment]
@benjycui 我想确认下，2.0的rc-form的mapPropsToFields是不是没有回滚之前的覆盖，我看了下源码，你好像做了deepMerge
