### ISSUE TITLE
Can not reset form by returning {} from `mapPropsToFields`.

### ISSUE THREAD

**Issue by ladjzero** [react-component/form#106]
To assign fields from `mapPropsToFields` to the inner form component is implemented, recently, as `Object.assign(this.fields, fields);`

As doc says:

mapPropsToFields: Convert props to field value. Usage example: reading the values from Redux store.

It would be reasonable that `mapPropsToFields` performs like react-redux/connect. What mapPropsToFields feeds, what the component inside gets. The previous code is quite OK I believe.

**Comment by ladjzero** [comment]
Refer to https://github.com/react-component/form/issues/104

**Comment by anianj** [comment]
我觉得更好的方式是给mapPropsToFields 传一个额外的参数控制是否需要全量更新

**Comment by benjycui** [comment]
Trace: https://github.com/react-component/form/issues/104
