### ISSUE TITLE
将Select组件封装后，无法利用getFieldDecorator来绑定此组件

### ISSUE THREAD

**Issue by kungcn** [react-component/form#115]
因为多处使用了同一个Select组件，故此封装起来，可以利用onChange函数使父组件监听该子组件的变化，但是使用setFieldDecorator赋值给该组件(如初始值)则无法起作用。

**Comment by yesmeck** [comment]
要把 props 都透传给 Select。

```javascript
const MySelect = (props) => <Select {...props} />;
```

**Comment by kungcn** [comment]
![default](https://user-images.githubusercontent.com/12772780/32542993-fbd02ee6-c439-11e7-99f4-66032d115a2e.png)

你好，打扰了，我昨晚看到以后思考了一下如果是这种使用场景的话要如何处理呢？<MySelect />就是我自己封装的Select组件，这样的话该如何传进去呢？

**Comment by yesmeck** [comment]
不明白你说的“如何传进去”的意思。

**Comment by kungcn** [comment]
就是要将此前通过setFieldValue赋值的test: 1中的1这样传进去额，好像是因为getFieldDecorator自动绑定到MySelect

**Comment by yesmeck** [comment]
看我二楼的代码。

**Comment by kungcn** [comment]
orz...我终于理解了，原来指的是将所有属性都传给MySelect而不是要用箭头函数传，谢谢！
