### ISSUE TITLE
Please do not use ES6 or ES7 in such a low-level library

### ISSUE THREAD

**Issue by gera2ld** [react-component/form#119]
`Array#includes` is used [here](https://github.com/react-component/form/blob/93cc37064e5b370e1b1978b8ddd085050702af84/src/createFieldsStore.js#L24), `String#startsWith` is used [here](https://github.com/react-component/form/blob/ab37ffbe2799cd8a05c3187b9f3fb622f3cc8b5c/src/createFieldsStore.js#L117). It breaks our application based on antd-mobile.

Maybe it's better not to use ES6 or ES7 features in such a low-level library?

**Comment by gera2ld** [comment]
@yesmeck https://github.com/react-component/form/blob/cbd480b1ebf74beb26f5aba11dc900754721f23e/src/createFieldsStore.js#L25

**Comment by yesmeck** [comment]
👌
