### ISSUE TITLE
validateFields 不会验证 setFields 中的 errors 

### ISSUE THREAD

**Issue by gutenye** [react-component/form#120]
例子:

```
form.setFields({name: {errors: ['name is required']}})
form.getFieldsError()      //-> {name: ['name is required']}
form.validateFields((errors, values) => {
   console.log(errors)        //-> errors is null, 这里应该是 {name: ['name is required']} 才对
   form.getFieldsError()     //-> {name: ['name is required']}
})
```

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by benjycui** [comment]
用 antd 里面的 Form.create

**Comment by gutenye** [comment]
@benjycui
 
地址:  https://codepen.io/gutenye/pen/ZaPWpd

重现步骤:
```
1. 点击 选择文件 按钮, 上传一个视频
2. 点击 Submit 按钮
3. 查看 Console 的输出
```

**Comment by benjycui** [comment]
无法重现。

![image](https://user-images.githubusercontent.com/3580607/33599847-604206f2-d9e2-11e7-9aec-d93268c6f5ab.png)

**Comment by gutenye** [comment]
@benjycui 

我简化了一下, 请查看这个: https://codepen.io/gutenye/pen/XzLOqx

```
1. 点击 Submit
2. 得到如下结果
```

<img width="308" alt="screen shot 2017-12-08 at 7 28 04 pm" src="https://user-images.githubusercontent.com/377544/33764119-16d01bb2-dc4e-11e7-9608-946cbe6cfcfb.png">

**Comment by benjycui** [comment]
`validateFields` 会重新计算 errors，之前的 error(包括你自行设置的) 会被扔掉，这是预期行为。

因为如果 `validateFields` 不重新计算 error，就没意义了，不是么？

**Comment by chocking** [comment]
@benjycui 请问怎么主动触发一次某个field的自定义validator? form.validateFields( ) 貌似不会触发

**Comment by benjycui** [comment]
Please provide a re-producible demo: https://u.ant.design/codesandbox-repro

**Comment by chocking** [comment]
@benjycui [https://codesandbox.io/s/3957nrzz6](url)
please have a check

**Comment by benjycui** [comment]
@chocking use `force: true`

```jsx
      this.props.form.validateFields({ force: true }, (err, values) => {
        ....
      });
```

**Comment by chocking** [comment]
@benjycui roger that

**Comment by liubin915249126** [comment]
@benjycui 我加了 { force: true }, 依然不行啊

**Comment by arcsin1** [comment]
加了force: true 也是不行 能不能真的有个办法解决

**Comment by LuJiaNan** [comment]
不要用validateFields去校验，用getFieldsError能否获取到设定的errors来判断是否通过校验
