### ISSUE TITLE
setFieldsValue传入的对象的值为null时，会触发一个js错误

### ISSUE THREAD

**Issue by modao** [react-component/form#122]
当使用Form的setFieldsValue(formData)为表单设置数据的情形。如果传入的formData对象的某个键值为null时，会触发一个js错误: [TypeError: Cannot convert undefined or null to object]

可以参看这个[demo](https://1857w4m803.codesandbox.io/)

**Comment by modao** [comment]
具体原因应该是由于utils.js中treeTraverse方法中只对tree参数做了为undefined的判断而遗漏了值为null的情形

**Comment by benjycui** [comment]
想了下，这个不是 bug，真正的问题在于你给一个还没注册的 name 设置值，这本来就是不支持的。

**Comment by yulidai** [comment]
遇到一样的问题，编辑时要载入原值 
所以调用setFieldsValue(formData); 报一样的错，延迟500毫秒才set一样报错
奇怪的是，我把formData打印出来，然后手工测试下是不是值类型不支持，结果却显示正常
类似：setFieldsValue({1: 1, 2:2, 3:3, 4:[], 5:moment.now})

formData打印出来和{1: 1, 2:2, 3:3, 4:[], 5:moment.now} 一模一样可是就是报错，有什么潜在的可能性么？
