### ISSUE TITLE
setFields或setFieldsValue场景下会有不应出现的warning

### ISSUE THREAD

**Issue by modao** [react-component/form#124]
在调用setFields或setFieldsValue场景下，会有下面的warning提示：

You must wrap field data with `createFormField`.

而根据文档，createFormField方法只在mapFieldsToProps时才需要使用

**Comment by benjycui** [comment]
提示信息需要优化而已，你的使用的确有问题，不能给还没注册的元素 setFields

**Comment by benjycui** [comment]
重装依赖后提示正常。

**Comment by modao** [comment]
不能setFields未注册的字段这个感觉有问题啊，有时候一个表单的数据会是从服务端获取的，服务端输出了冗余数据，难道还要过滤一遍？冗余数据Form这边直接丢弃掉就好了啊

**Comment by mingzepeng** [comment]
@modao  我同意你的看法，如果我这边注册了二三十个字段，服务端给了五六十个字段，还得重新过滤一遍么，这种过于严谨的设计就有点反人类
