### ISSUE TITLE
getFieldDecorator 中使用 option.hidden 会导致一些意外

### ISSUE THREAD

**Issue by HunDunDM** [react-component/form#127]
### `resetFields`

如果一个field被设置成`hidden: true`，就无法使用`resetFields`重置，哪怕是参数中指定。

### `getFieldDecorator`

被绑定的input组件，在重新设置`hidden: false`后，且实际绑定的input组件实例和hidden前不一致的情况下，则在下一次render的时候才会获得被隐藏前的value。并且在console中会警告`You cannot set field before registering it.`。

### 原因推测

`getValidFieldsName` 函数来处理hidden。而2.x中部分函数使用该函数来获取完整列表。（和1.5.0版本不一致）导致无法处理hidden标记的field。包括`resetFields` `flattenRegisteredFields`

### 复现代码

    import React, { Component } from 'react';
    import { Form, Input, Button } from 'antd';

    @Form.create()
    class App extends Component {
      state = { hidden: false };
      render() {
        const { form } = this.props;
        const { hidden } = this.state;
        const decorator = form.getFieldDecorator('input', { hidden });
        // 以下两种不论采用哪种写法，均出现hidden后无法reset
        /* 此写法，在设施hidden为true后，console 正常警告 You cannot set field before registering it.
         * 重新设置为 false 后表现依旧正常
         */
        // const input = decorator(<Input />);
        /* 此写法，在开始hidden为false，并输入数据后，设置hidden为true，再设置false后，
         * 此时由于input中间被渲染为null，所以前后的input实例不一致
         * 一开始会先显示空白，并在任意输入字符触发render后闪烁回hidden前数据。
         * 同时 console 显示 You cannot set field before registering it.
         * 个人认为hidden第一次重新设置为false时，getFieldDecorator疑似没有获得正确的参数
         */
        const input = hidden ? null : decorator(<Input />);
        return (
          <div>
            <Button type="primary" onClick={() => this.setState({ hidden: false })}>visable</Button>
            <Button onClick={() => this.setState({ hidden: true })}>hidden</Button>
            <Button type="danger" onClick={() => form.resetFields()}>reset</Button>
            {input}
          </div>
        );
      }
    }

    export default App;

### 关联issue

[ant-design#8560](https://github.com/ant-design/ant-design/issues/8560)

**Comment by benjycui** [comment]
`hidden` only affect validation and getter.

**Comment by HunDunDM** [comment]
I'm sorry, this problem is still not completely solved. Please reopen this issue.
console would not log `You cannot set field before registering it.` now. However, it would still roll back to the data before the reset.
Then I find that the problem may not have relation with `hidden`. I'm sorry to have provided the wrong idea before.

    import React, { Component } from 'react';
    import { Form, Input, Button } from 'antd';

    @Form.create()
    class App extends Component {
      state = { hidden: false };
      render() {
        const { form } = this.props;
        const { hidden } = this.state;
        // const decorator1 = form.getFieldDecorator('input1', { hidden });
        // const input1 = hidden ? null : decorator1(<Input />);
        // const decorator2 = form.getFieldDecorator('input2', { hidden });
        // const input2 = hidden ? null : decorator2(<Input />);
        const input1 = hidden ? null : form.getFieldDecorator('input1')(<Input />);
        const input2 = hidden ? null : form.getFieldDecorator('input2')(<Input />);
        return (
          <div>
            <Button type="primary" onClick={() => this.setState({ hidden: false })}>visable</Button>
            <Button onClick={() => this.setState({ hidden: true })}>hidden</Button>
            <Button type="danger" onClick={() => form.resetFields()}>reset</Button>
            {input1}
            {input2}
          </div>
        );
      }
    }

    export default App;

**Comment by HunDunDM** [comment]
[![Edit o4nwr2x7z](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/o4nwr2x7z)

**Comment by benjycui** [comment]
Please provide steps to re-produce, instead just throw a pile of code and let others guess.

**Comment by HunDunDM** [comment]
update the steps to re-produce

**Comment by benjycui** [comment]
@afc163 see: https://github.com/react-component/form/pull/117

**Comment by benjycui** [comment]
`option.hidden` works fine now, @HunDunDM what you met is another issue.

**Comment by HunDunDM** [comment]
thanks.

**Comment by HunDunDM** [comment]
The reason seems to be that the cache cannot be reset.

**Comment by afc163** [comment]
> resetFields需要清除clearedFieldMetaCache中对应的缓存

@HunDunDM PR is welcome~

**Comment by HunDunDM** [comment]
submit a [PR](https://github.com/react-component/form/pull/128)

**Comment by HunDunDM** [comment]
fixed by #128 #129
