### ISSUE TITLE
触发两次setFieldsValue，会导致this.fieldsMeta缺少数据

### ISSUE THREAD

**Issue by kasinooya** [react-component/form#13]
![aa](https://os.alipayobjects.com/rmsportal/aSQbIjWTrsMfAKK.png)

触发两次setFieldsValue, this.fieldsMeta中会少数据

![bb](https://os.alipayobjects.com/rmsportal/vBACFPLnZgIfZto.png)

这两个值不一致

**Comment by benjycui** [comment]
试了下，并没有。。。

![image](https://cloud.githubusercontent.com/assets/3580607/14662762/f7e60aec-06eb-11e6-97bc-72bfbd1e693e.png)

能提供 100% 重现的步骤？

**Comment by kasinooya** [comment]
this.fieldsMeta 和 this.fields的区别是什么？获取 nowValues 为什么不去遍历 this.fields

**Comment by benjycui** [comment]
`this.fieldsMeta` 里面是的 `rules` 和 `trigger`，和 `this.fields` 里面不一样的，你可以打出来年年，不过一般情况下不需要关心吧。。

**Comment by yiminghe** [comment]
resolved
