### ISSUE TITLE
not validate immediately after changing rules (without events in validateTrigger fired)

### ISSUE THREAD

**Issue by reallyimeric** [react-component/form#130]
sample to reproduce:

[![Edit n06kk6y120](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/n06kk6y120)

**Comment by reallyimeric** [comment]
and the issue affects antd Form

**Comment by benjycui** [comment]
Please provide steps to re-produce, and expected behavior

**Comment by reallyimeric** [comment]
## to reproduce

1. render a input field with `getFieldProps`
2. rerender the component and change the rules

## expected behavior

validate fields with changed rules

## current behavior

does not validate after rerendering

**Comment by yutingzhao1991** [comment]
@reallyimeric your demo is works in my browser.
![temp](https://user-images.githubusercontent.com/1061968/34337607-c8f9786a-e99b-11e7-8c84-4791eea9367f.gif)

**Comment by reallyimeric** [comment]
@yutingzhao1991 As you can see, getFieldError did not get the error until next inputing. Is it expected?

**Comment by afc163** [comment]
I think it is intented behavior, validation happen only when input is changed.

**Comment by yutingzhao1991** [comment]
@reallyimeric yes, it id expected.

@afc163 But can't get error when I try to trigger `validateFields` after validator changed,  Is it a bug ? ref: https://codesandbox.io/s/3yz3wk8w65 .

**Comment by afc163** [comment]
Try `force` option of `validateFields`: https://codesandbox.io/s/v1v61y8kv5

https://github.com/react-component/form#optionsforce-boolean
