### ISSUE TITLE
form 表单持久化存储数据

### ISSUE THREAD

**Issue by callmez** [react-component/form#132]
代码演示: https://codepen.io/callmez/pen/LebvJj

只要上层组件`App`有变动(和form需要的props无关变动,), form组件就得重新初始化. 有没有方法保留form的数据变动

例如:  点击确定, form数据ajax提交, 这段时间确定按钮由上层组件的submiting来控制disabled, 提交成功关闭modal, 提交失败继续保留form数据,  

现在的情况是只要上层组件一变动. form就重置

**Comment by yutingzhao1991** [comment]
你用了`mapPropsToFields`，你里面的逻辑会使得表单的值和 props 同步，要么去掉 mapPropsToFields ，要么在表单数据改变后同步到上层。

**Comment by callmez** [comment]
如果按照你说的增加一个同步到上层的函数, 还是会有一个问题, 

form的验证记录会因为同步到上层了导致props又变更 然后验证记录也会被清空(只是想保留form的数据给用户一个直观的反馈),  

这样根本不能很好的持久化处理form表单.   我觉得这里有一个逻辑流程上的误导.
