### ISSUE TITLE
antd Form.create({}) 时报错

### ISSUE THREAD

**Issue by elowes** [react-component/form#133]
看了最后报错的地方是 rc-form@2.1.7 的 utils.js 文件。另外此问题只在部署生产时 webpack 打包后才存在，开发时一切正常。实在让我很费解，可否有人能提出点建议。
![image](https://user-images.githubusercontent.com/8766034/34352814-a6320a3a-ea5f-11e7-9901-4505a08a1d10.png)

**Comment by yutingzhao1991** [comment]
很像今天看到的一个类似的问题，应该是构建的问题，uglify-es 升级导致，先用 uglify-es  3.2.2 版本

**Comment by yesmeck** [comment]
https://github.com/mishoo/UglifyJS2/issues/2657
