### ISSUE TITLE
why some browser autoComplete and still trigger required error ?(为什么有些浏览器记住密码自动填充后依然触发require的表单验证的错误呢)

### ISSUE THREAD

**Issue by MrZWH** [react-component/form#136]

**Comment by yutingzhao1991** [comment]
I guess the reason is browser did not trigger change event after auto fill value. Can you give more information about this.

- Witch browser?
- Give a reproduction link or a gif.

**Comment by MrZWH** [comment]
@yutingzhao1991 

- the browser is 360 SECURITY BROWSER![](http://p1.qhimg.com/d/inn/e2760a50/logo.jpg),it have two browser kernel(IE and webkit).

- I use Ubuntu, I don't know how to do gif.(┬＿┬）  

 i also think browser did not trigger change event.
```js
<FormGroup >
  <Label>账号</Label>
  {getFieldDecorator('loginNo', {
    rules: [
      {required: true, message: '请输入您的账号'},
        {
          pattern: /^[A-Za-z0-9]+$/,
          message: '请输入有效账号!'
        }
     ]
  })(
     <Input
       type="text"
       autoComplete="off"
       onBlur={onUsernameBlur}
       placeholder="请输入您的账号"
      />
    )}
</FormGroup>
<FormGroup >
  <Label>密码</Label>
    {getFieldDecorator('password', {
      rules: [
         {required: true, message: '请输入您的密码'}
      ]
     })(
    <Input
        type="password"
        placeholder="请输入您的密码"
    />
    )}
</FormGroup>
```
When I trigger the submit button, it displays the error of the required...

**Comment by XavierLeTohic** [comment]
I cant see in your code that you are using a library of the `Input` component right ?
Did you try with a default input if you get the same problem ?

**Comment by MrZWH** [comment]
@XavierLeTohic  I wrote the Input component
```js
export class Input extends React.Component {
  render() {
    return (
      <input {...this.props} className={styles.input} />
    )
  }
}
```
No other attributes are added.My front-end technology level is not high,is my question a little meaningless?(￣□￣)

**Comment by XavierLeTohic** [comment]
@MrZWH no, I asked you because I already encountered this problem with this package.

I tried on the lastest version of **Firefox** and get the same issue as you can see in the gif below :

![rc-form-autofill](https://user-images.githubusercontent.com/6340490/35085280-3d600c20-fc28-11e7-8463-7c0d5c5d44a4.gif)

**Comment by XavierLeTohic** [comment]
@MrZWH I replaced my `Input` component from a UI library by a native HTML input element and it's working.

I really don't know how to fix this 🤔

**Comment by MrZWH** [comment]
@XavierLeTohic ok,thank you very much

**Comment by benjycui** [comment]
We are not going to support 360. If you cannot re-produce this bug with modern browser, we will ignore it, thanks.

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/NdQdBw?editors=0011

**Comment by MrZWH** [comment]
@benjycui Other browsers have no problem,thanks
