### ISSUE TITLE
和antd-mobile的form组件一起使用出现问题

### ISSUE THREAD

**Issue by itxuye** [react-component/form#141]
![wechatimg682](https://user-images.githubusercontent.com/9589686/35729213-fbfb16d0-0848-11e8-98ee-794a3b447afb.jpeg)

没有使用stateless的组件，就只使用了antd-mobile的form组件

**Comment by yesmeck** [comment]
提供在线的重现 demo

**Comment by itxuye** [comment]
@yesmeck 因为我是个input array，使用index当做key，但是我的这个input array是变化的，使用index就会有问题，现在在数据里面加上了唯一且稳定的key可以就好了
