### ISSUE TITLE
input输入的时候报warning

### ISSUE THREAD

**Issue by Loserhua** [react-component/form#146]
Form is changing an uncontrolled input of type undefined to be controlled. Input elements should not switch from uncontrolled to controlled(or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components

**Comment by Loserhua** [comment]
发现设置initialValue后不会有这个问题，但是难道一定要设置initialValue吗？是什么原因呢？

**Comment by yesmeck** [comment]
> 但是难道一定要设置initialValue吗

是的。原因如 warning 所说。

**Comment by Loserhua** [comment]
@yesmeck 没有设置value啊
![image](https://user-images.githubusercontent.com/18026287/36586067-4275f3c8-18bb-11e8-8ed3-518e150ba4cf.png)

**Comment by yesmeck** [comment]
设置一个 `initialValue`.

**Comment by Loserhua** [comment]
@yesmeck 只有这个办法吗?因为所有的设置initialValue为" "感觉很多余

**Comment by yesmeck** [comment]
是的，目前只能设置 `initialValue`。

**Comment by Loserhua** [comment]
@yesmeck 好的，谢谢
