### ISSUE TITLE
onFieldsChange is firing twice

### ISSUE THREAD

**Issue by daydream05** [react-component/form#148]
onFieldsChange is firing twice whenever I change my field. Looking at my state, it seems that it turns "dirty" and "validating" from false to true. Is this an expected behavior?

**Comment by yesmeck** [comment]
Yes, it's an expected behavior.

**Comment by allocenx** [comment]
Why?????

**Comment by daviemakz** [comment]
+1

**Comment by yoyo837** [comment]
See https://github.com/react-component/form/issues/156#issuecomment-381543089
