### ISSUE TITLE
rc-form@0.15.2 does not work with antd@1.0.0-beta.2

### ISSUE THREAD

**Issue by TheWaWaR** [react-component/form#15]
Error info in `createBaseForm.js`
```
Uncaught TypeError: Cannot read property 'instance' of undefined
```

However, rc-form@0.15.1 is OK.

**Comment by benjycui** [comment]
Here is the problem https://github.com/react-component/form/commit/ca9f6974dd7de97a91311ef07626aa520943f1cf ...

**Comment by benjycui** [comment]
And could you provide a re-producible demo: http://codepen.io/anon/pen/pgdXYp?editors=001

I need more info.

**Comment by benjycui** [comment]
I had re-produce this bug in http://react-component.github.io/form/examples/input-array.html

Will fix it soon.

**Comment by TheWaWaR** [comment]
👍
