### ISSUE TITLE
How do you setFieldsInitialValue() of a contextual field?

### ISSUE THREAD

**Issue by jwmann** [react-component/form#150]
Here is a reconstruction of my example.
https://codesandbox.io/s/koqnkq4335

I need fields to be shown contextually to the answers of other questions.
But I need to be able to set the initialValue of these fields on a wide scale using `setFieldsInitialValue()`

Unfortunately, these fields don't 'register' until they actually render on the page. Leading to the error `You cannot set field before registering it.`

How do I do this then?

**Comment by benjycui** [comment]
Just hide fields with CSS.
