### ISSUE TITLE
how to remove or cancel errors by setFields

### ISSUE THREAD

**Issue by hanhanyaobiancheng** [react-component/form#151]
i try to use setFields({
    name: {errors: []},
}) or by setFields({
    name: {errors: null}
}) or just setFields({
    name: {value},
}) to cancel the errors but the component which i setFieds is still exist, only the error message gone; the border of the component is still in error color red, how can i resolve this

**Comment by benjycui** [comment]
> the border of the component is still in error color red, how can i resolve this

It is not an issue of rc-form, but an issue of your UI component

**Comment by hanhanyaobiancheng** [comment]
I really don't undertand; my UI component is just a Input component of antd; why  it do not work with antd Form Component

**Comment by benjycui** [comment]
It is an issue which should be file in antd, not rc-form.
