### ISSUE TITLE
How do you update Form from a controlled component?

### ISSUE THREAD

**Issue by jwmann** [react-component/form#153]
I have a wrapper component that changes default behaviour of how the value is formatted.
This component works and updates the value just fine. However, since I'm overwriting `onChange` and `value` as shown in multiple of the [examples](https://github.com/react-component/select/tree/59ad5ed6113d8873b20078be58beeaca661ca18b/examples). The `getFieldDecorator` won't detect and changes.

Even if the literal value of the input is what it should be, the form is still `null`

Here's a sandbox of what I'm trying to do:
https://codesandbox.io/s/ko1r44l3k3

I'm trying to get the value of "autocomplete" to be the label of the option you select. e.g. "Hello" or "World"

**Comment by benjycui** [comment]
I don't understand. Please provide steps to re-produce your issue, and what is your expected behavior.

**Comment by benjycui** [comment]
Actually, this works as expected. rc-form store value that the field need.

In your demo, select needs values like 1 & 2, so that rc-form just store 1 & 2.

**Comment by jwmann** [comment]
@benjycui I feel like you are not fully understanding what I'm trying to explain. Please allow me to elaborate.

_I have also updated my sandbox to fully reflect the issue._
https://codesandbox.io/s/rwyxm79nym

SuperSelect is a wrapper component which is controlling the `onChange` and `value` props of the Autocomplete component.

1. Type "Hello" into the Autocomplete.
2. Select "Hello" from the dropdown menu
3. Take note that the Value of the Input is the label (e.g.: "Hello") (this is what I want)
4. Note that the JSON has not detected a Form onChange event
5. Select Autocomplete once more, notice that the JSON now detects an onChange event
6. JSON values of the Form show `{ autocomplete: null }`, it _should_ read `{autocomplete: "Hello"}`

Here's a GIF incase the steps or the link don't work.
![screen capture on 2018-03-27 at 00-46-49](https://user-images.githubusercontent.com/436270/37947320-7834d33e-3158-11e8-80be-3d5499b8095c.gif)

**Comment by benjycui** [comment]
You had override onChange, so that rc-form cannot collect value from AutoComplete.

![image](https://user-images.githubusercontent.com/3580607/38179692-bca6e19c-3658-11e8-86f7-a0d1c836dd57.png)

**Comment by jwmann** [comment]
@benjycui Yes, that's exactly what I'm saying. I realize that's why it doesn't see the value but I _need_ to be able to modify the value.
**Is there a way to tell the Form what the value is from within my controlled component?**

For example, in Redux Form, it would pass the `onChange()` function to the component as a prop.
So I would be able to update the form by doing this `this.props.input.onChange( 'Hello' );`
Here's the docs for reference https://redux-form.com/7.3.0/docs/api/field.md/#-code-input-onchange-eventorvalue-function-code-

But rc-form doesn't seem to pass anything useful to the component as a prop. Just static values.
There must be _something_ similar right?

**Comment by benjycui** [comment]
Just call this.props.onChange in your onChange.

**Comment by jwmann** [comment]
Hahaha wow, that exactly what I needed. Thanks!
I wish there was better documentation on that but hopefully someone else who's as confused as me will find this thread and find it helpful. Here's the final updated controlled component version
https://codesandbox.io/s/yjo4xmkl81

Thanks @benjycui for taking the time help me and letting me explain my problem in such an elaborate way. 👍
