### ISSUE TITLE
how to delete the filed benn register

### ISSUE THREAD

**Issue by Ai01** [react-component/form#160]
```js
const { getFieldDecorator } = form;
getFieldDecorator('name', { initialValue: 'test' })
```
how to delete the filed `name`? thank you.

**Comment by mintsweet** [comment]
```
const { resetFields } = form;
resetFields('name');
```
I think it should be this method.

**Comment by Ai01** [comment]
@mintsweet 
l mean delete the field "name" not the "name" field's value "test". 
`resetFields` can delete the value of field can't delete the field;

**Comment by mintsweet** [comment]
oh, sorry.
It should not has a method to help you delete field "name" .
Maybe you can manually delete.

**Comment by benjycui** [comment]
Just unmount the component which is register.

**Comment by Ancinek** [comment]
As far as I know, the field is still registered then even if the component that registered it was removed. I would have to unmount the component with the form itself.

Thanks anyway.

**Comment by Ancinek** [comment]
@Ai01 As far as I know there is no way to do it still? Please correct me if I'm wrong.
There is new form API discussion here https://github.com/ant-design/ant-design/issues/10640, so maybe you can propose a solution (like a method called `removeFieldDecorator`). Not sure though if this issue is to post feature request or just to discuss the hooks vs. props

**Comment by jwmann** [comment]
I'm also looking to have this functionality.

I have dynamic fields set up as per the Ant Design example https://ant.design/components/form/#components-form-demo-dynamic-form-item

However, I need to keep the form object to show another step of the submission process.
Luckily, `getFieldDecorator()` has a nice option called `preserve: true` that does exactly that.

Unfortunately though, this doesn't work nicely with dynamic fields.
When the user removes a field, the field stays in the form object, which is expected as the field is set to preserve.

I'd need a way to manually remove this field from the form object programmatically without relying on the mount/unmount of the page.
