### ISSUE TITLE
React 16.3 getDerivedStateFromProps support

### ISSUE THREAD

**Issue by fantua** [react-component/form#163]
```
Warning: Unsafe legacy lifecycles will not be called for components using new component APIs.

Form(MyConponent) uses getDerivedStateFromProps() but also contains the following legacy lifecycles:
  componentWillReceiveProps
```

Any plans to support `getDerivedStateFromProps` and remove async-unsafe `componentWillReceiveProps`?

**Comment by benjycui** [comment]
Yep, but it is not easy.

Ref: 

https://github.com/react-component/form/blob/36b8a1d3399d1e9ab9329eba6dce843691e0efe0/src/createBaseForm.js#L73-L77

**Comment by Kexin-Li** [comment]
I'd like to working on this~
