### ISSUE TITLE
Dynamic form handling

### ISSUE THREAD

**Issue by Ancinek** [react-component/form#166]
I'm using the `rc-form` inside `antd` package and I really love it.

I had to do a dynamic form, when the user can add /remove rows that contains form fields.
One issue that I encounter is if I remove the row from the DOM it is not deleted in the form state, but that is how it should be. However, let have the following example:

1. Add to the form state `records` position:
```
form.getFieldDecorator('records', { initialValue: [] });
```
2. Add dynamically a row that and register it using 
```
form.getFieldDecorator('records[0].attribute_name');
```
3. Now the `form.getFieldsValue()` returns a `records` array with 1 position inside.
However if I try to do the following after removing the row with the form fields, I still get a `records` array from `form.getFieldsValue()` with 1 position inside
```
form.setFieldsValue({ records: [] });
```

**My question** - is it possible to `unregister` the previously registered field?

**Comment by benjycui** [comment]
You cannot use `records` and `records[0]` in the same form.
