### ISSUE TITLE
set `first:true` when validating don't work as same as expected

### ISSUE THREAD

**Issue by hezhii** [react-component/form#167]
I set the option `first:true` when I call the `form.validateFields`.

>first: Boolean, Invoke callback when the first validation rule generates an error, no more validation rules are processed. 
>see https://github.com/yiminghe/async-validator#options

It works well at the first validation, I will get the first error. But after fix the first field error and validate again, It will not check the rules of other fields.And if i set the first field correctly at first validation, it will check the second field.

Now I set the `force true`, it can work well.Does this mean I have lost the validation cache？Is this a normal appearance？

My code is like this.

```js
submit = () => {
  const { form } = this.props
  form.validateFields({ first: true }, (err, values) => {
    if (err) {
      console.log(err)
    }
  })
}

render(){
  return (
    ...
    <Input
      {...getFieldProps('username', {
        rules: [{ required: true, message: 'require username' }]
      })}
    >UserName</Input>
    <Input
      {...getFieldProps('password', {
        rules: [{ required: true, message: 'require password' }]
      })}
    >Password</Input>
    ...
  )
}
```

**Comment by benjycui** [comment]
It is right to set `force: true`.
