### ISSUE TITLE
feat: `validateFieldsAndScroll` 应允许配置滚动入屏后距离顶部的高度

### ISSUE THREAD

**Issue by benjycui** [react-component/form#17]
Relative: https://github.com/ant-design/ant-design/pull/1011#discussion_r61984180

增加参数，用以配置 `scrollIntoView`  的 [config](https://github.com/yiminghe/dom-scroll-into-view#function-parameter)。

**Comment by benjycui** [comment]
在原来 `option` 的基础上，增加 `scroll` 如何？ @yiminghe 

```js
{
  force: true,
  scroll: {
    offsetTop: 18,
    ...
  } ,
  ...
}
```

**Comment by yiminghe** [comment]
https://github.com/react-component/form/blob/master/src/createDOMForm.jsx#L73

直接增加 options.config

**Comment by benjycui** [comment]
只是觉得 `options.scroll` 比 `options.config` 语义会好点？

**Comment by yiminghe** [comment]
ok
