### ISSUE TITLE
Middleware function to edit output value of form field

### ISSUE THREAD

**Issue by pellejacobs** [react-component/form#175]
Is it possible to add a middleware function to edit the output a form field gives back to the form on submit? 

It seems like, currently, to only way to edit an output value, is by doing it after submission, as in the Ant Design docs demo: https://ant.design/components/form/#components-form-demo-time-related-controls 

I would imagine to add a function as an option to `getFieldDecorator` that is run on submission, takes the value of the field and return the value the submission function receives. 

This would allow all logic related to a single Form Item to be integrated in that form field, creating less dependencies within the code. 

The example of a datepicker, could look like this: 

```javascript
<FormItem>
  {getFieldDecorator('date-picker', { onSubmit: (value) =>  value.format('YYYY MM DD')} )(<DatePicker/>)}
</FormItem>
```

**Comment by benjycui** [comment]
Nope, will not support this feature. It is unnecessary/

**Comment by pellejacobs** [comment]
Cool, anyway, thanks for considering!

**Comment by kaikun213** [comment]
This could help also in Selection cases e.g.

It adds up unnecessary complexity when transforming some fields in the submission again, especially when having nested components with own getFieldDecorators. Then onSubmit should only check for errors and do less preprocessing of nested objects. Please reconsider.

```
<Form.Item>
            {getFieldDecorator('dataIndex', {
              initialValue: object.id,
              transform: (objId) => objects.find(o => o.id === objId)
            })(
             <Select>
                {objects.map(o => (
                  <Select.Option key={o.id} value={o.id}>
                    {o.name}
                  </Select.Option>
                ))}
              </Select>,
            )}
</Form.Item>
```
