### ISSUE TITLE
Doesn't go inside validateFields completion

### ISSUE THREAD

**Issue by iphonic** [react-component/form#177]
This is my Form declaration

```
<Form onSubmit={this.handleSubmit.bind(this)}>
<Button  type="primary" htmlType="submit" name="saveandcreate" disabled={hasErrors(getFieldsError())} >Save</Button>
</Form>
```

and following is the declaration of **handleSubmit** function

```
handleSubmit = (e) => {
      e.preventDefault();
      this.props.form.validateFields((err, values) => {
        if (!err) {
          console.log('Received values of form: ', values);
            this.justSave(values,this.state.buttonType);
       }
   });
}
```

It never goes inside **validateFields** function in the above code though handleSubmit function get called, **this.props.form** is valid too. I don't understand why it doesn't work, thus I can't proceed to send values to server.

Thanks.

**Comment by benjycui** [comment]
Please provide an online demo.

**Comment by iphonic** [comment]
Please find the online demo here https://codesandbox.io/s/rlx6lkon74. Thanks. @benjycui

**Comment by benjycui** [comment]
It works fine, see: https://codesandbox.io/s/ll2jy7q7wl

**Comment by iphonic** [comment]
No it doesn't work if you see `handleSubmit` function the console.log doesn't execute, that should execute, it doesn't go inside the `this.props.form.validateFields()` completion other than that, everything works fine.

Thanks.

**Comment by iphonic** [comment]
Hi @benjycui are you able to help me? I am really stuck in here, Thanks.

**Comment by benjycui** [comment]
> It works fine, see: https://codesandbox.io/s/ll2jy7q7wl

See my demo.

**Comment by iphonic** [comment]
I have checked your demo, it doesn't work, anyways I found the problem, the phone number validator was creating problem, I replaced the validator with rules it works.
