### ISSUE TITLE
Localization validationMessages

### ISSUE THREAD

**Issue by EstebanBP** [react-component/form#178]
Hi!
Is there anyway to change validationMessages option to support multilanguage?
Im looking for an alternative to:

```
export const form1 = createForm({ validateMessages: englishMessages})(MyForm);
export const form2 = createForm({ validateMessages: spanishMessages})(MyForm);
export const form3 = createForm({ validateMessages: frenchMessages})(MyForm);
....
```

**Comment by benjycui** [comment]
https://github.com/react-component/form/blob/61e0e69c0e316235d61ebc194deeee329dcbd62f/examples/overview.js#L20-L25

**Comment by benjycui** [comment]
You can use react-intl in message.
