### ISSUE TITLE
onFieldsChange 的 fields 参数各字段中 ‘instance’ 属性存在循环结构，导致 Redux DevTools 报错

### ISSUE THREAD

**Issue by clarkhan** [react-component/form#19]
目前将 fields 直接存储到 redux store 中，但是会遇到如下的错误：

```
VM3378:21 Uncaught TypeError: Converting circular structure to JSON
```

经排查后发现这是 Redux DevTools 报的错，由 fields 各字段中的 'instance' 引起，在 dispatch 前删掉就可以正常。

现在想问下，这个属性的作用是什么，可以删掉吗？如果删掉没问题最好还是在 onFieldsChange  的参数中就干掉。

**Comment by benjycui** [comment]
https://github.com/react-component/form#notes

@yiminghe 或者可以整理为：

* `this.fieldsMeta` 开发者指定的信息，如：`validateTrigger` `rules`
* `this.fileds` 动态生成且可以序列化的信息，如：`value` `errors`
* `this.xxx` 动态生成且不可以序列化的信息，如：`instance`

**Comment by yiminghe** [comment]
@benjycui  instance 放到 this.fieldInstances 上吧

**Comment by benjycui** [comment]
主要是顾虑都以后会不会还有类似 `instance` 的字段再现。。
