### ISSUE TITLE
自定义控件如何支持 getFieldsValue？

### ISSUE THREAD

**Issue by lawrsp** [react-component/form#22]
form里有个自定义控件，get出来的还是传进去的initialValue

类型的场景还有：想修改Input里输入的值作为value，比如整理一下格式

**Comment by benjycui** [comment]
请确认你的自定义控件提供了 `onChange` 方法，另外提问时建议提供可重现 demo, THX!

Please provide a re-producible demo: http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by lawrsp** [comment]
@benjycui 
已经解决，因为是文档里没写，不知道怎么实现，后来看代码，发现需要onChange

但是，还有个问题：
onChange只支持String类型的，能否放宽一下，支持任意类型？

**Comment by benjycui** [comment]
应该没有限制类型，可以详细描述下你的使用场景么？

**Comment by benjycui** [comment]
无进一步反馈，关了。
