### ISSUE TITLE
Unknown prop `__meta` on <input> tag

### ISSUE THREAD

**Issue by afc163** [react-component/form#23]
```
"Warning: Unknown prop `__meta` on <input> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
```

`__meta` 在这里是有用的，不太好去掉，看看有没有别的方式来处理。

https://github.com/ant-design/ant-design/issues/2258

**Comment by yiminghe** [comment]
https://github.com/ant-design/ant-design/commit/3d9ae9833e75bcf8db5a41c86fb59c36bd17454d
