### ISSUE TITLE
未注册的字段，通过调用getFieldValue或getFiledsValue却被自动注册成了表单元素。

### ISSUE THREAD

**Issue by jssoscar** [react-component/form#237]
![image](https://user-images.githubusercontent.com/4252175/51105275-83764900-1823-11e9-9b80-52369866f3cb.png)
如图代码，为了测试，在didMount中  特意直接调用了一次getFieldsValue方法
通过getFieldDecorator只注册了一个name的input表单元素，按道理来说，最后获取表单数据时候得到的对象，应该是{name: ''}
然而实际得到的结果是：
![image](https://user-images.githubusercontent.com/4252175/51105359-bfa9a980-1823-11e9-80d0-1cbbcb4ff4e4.png)

未注册的字段，通过调用getFieldValue或getFiledsValue却被自动注册成了表单元素。

**Comment by zombieJ** [comment]
升级一下你的 rc-form 版本。
