### ISSUE TITLE
how to map array of object to field

### ISSUE THREAD

**Issue by alayii** [react-component/form#24]
数据结构类似于：

```
{
  title: 'test',
  items: [{
    id: 1
    title: 'xxx'
  }, {
    id: 2
    title: 'xxxx'
  }]
}
```

根据 [input-array](http://react-component.github.io/form/examples/input-array.html) 这个例子，
先使用
```
getFieldValue('items').map
```

但是 map 里的 input 怎么关联到 id 和 title 这样的字段呢

```
{...getFieldProps('item.title')}
```
并没有生效

**Comment by benjycui** [comment]
`getFieldProps` 第一个参数必须唯一，所以应该这样:

```js
`item${index}.title`
```

**Comment by benjycui** [comment]
研究下这两个例子：

http://react-component.github.io/form/examples/input-array.html

http://react-component.github.io/form/examples/checkbox-group.html

**Comment by alayii** [comment]
```
getFieldValue('items').map((item, index) => (
  <Input
    {...getFieldProps(`item${index}.title`)}
  />
));
```

input 里还是没有值出现，打印了下 fields，{ name: item0.title } ，并没有 value 值

貌似没找到可在 codepen 直接引用的 js ，不太好做示例呃

**Comment by alayii** [comment]
write as below, you need `initialValue` to let it display in input.

 then in `onFieldsChange` function (usually redux reducer) to update relate value.

like split prop string (eg: item.0.title), get index, then update.

```
getFieldValue('items').map((item, index) => (
  <Input
    {...getFieldProps(`item.${index}.title`, {
      initialValue: item.title,
    })}
  />
));
```

设置 initialValue 后让它显示，然后在 onFieldsChange 去更新相关的值，就可以了
