### ISSUE TITLE
Add the `withRef` option's description into docs.

### ISSUE THREAD

**Issue by anson0370** [react-component/form#25]
This option is really helped sometimes and I found it from the sources. No any description of it in readme.

And maybe descibe it in antd's doc too?

**Comment by benjycui** [comment]
Could you create a PR? Thanks.

Actually, any advice on documentation could be a PR. It's better than an issue.

**Comment by anson0370** [comment]
Of course. I will leave this issue here and make a PR later. But because the hard work, I'm not sure when the PR can be done. Maybe today or this weekend. 😄
