### ISSUE TITLE
强制插入了 value props

### ISSUE THREAD

**Issue by warmhug** [react-component/form#3]
![image](https://cloud.githubusercontent.com/assets/2011119/12200050/7faba288-b657-11e5-8962-1ce55d638bfd.png)

代码里这个逻辑必然会进来，是正确的？验证状态就不能只设置 defaultValue 了吗？除了input外 select 、tree-select 都有 defaultValue，不受控也应该可以被验证的

**Comment by yiminghe** [comment]
不支持不受控

**Comment by warmhug** [comment]
Select 上设置value为数组和初始值，会有问题

**Comment by warmhug** [comment]
没问题了，是使用的不对。（高阶组件 form 拦截用户设置的 onChange，用起来还是很迷惑人的，不过也没想出什么其他更好做法），还是没ng的验证用着简单~
