### ISSUE TITLE
请问提交时如何过滤disabled为true的表单控件

### ISSUE THREAD

**Issue by bailihuiyue** [react-component/form#306]
请问提交时如何过滤disabled为true的表单控件,如题,万分感谢

**Comment by lich-yoo** [comment]
提交时，你很难介入库实现。你说的问题 完全可以在设置 rule 时设置你想要的效果。
 rules: [{ required: required && !disabled, ... }...]
ps: 我觉得 校验规则统一处理会更方便些

**Comment by bailihuiyue** [comment]
已解决,在getFieldDecorator中加入hidden即可
