### ISSUE TITLE
How to clear fields after submitting form?

### ISSUE THREAD

**Issue by jahmaiosullivan** [react-component/form#31]
For the life of me I can't seem to figure out how to clear the input boxes after submission.

resetFields doesn't work. setInitialiValues doesn't work. Very frustrating!

**Comment by jahmaiosullivan** [comment]
Ok I found setFieldValue which works. I still haven't found a use for resetFields.

**Comment by millionbug** [comment]
hi friend , how to make the fucking 'setFieldvalue' work? and how to use setInitialiValues?
