### ISSUE TITLE
请问自定义的组件怎么使用getFieldProps和validator？

### ISSUE THREAD

**Issue by mervynyang** [react-component/form#32]
`
    checkPass(rule, value, callback) {
    callback();
  }
`
value的值是怎么获取到的呢？自定义的组件不是input，是一个相册选择

**Comment by yiminghe** [comment]
默认 value 从 onChange 第一个参数取得

**Comment by mervynyang** [comment]
好的 谢谢

**Comment by ChinaShrimp** [comment]
In case somebody reach here through google, here is the link: https://ant.design/components/form-cn/#components-form-demo-customized-form-controls
