### ISSUE TITLE
Warning when using legacy lifecycle methods

### ISSUE THREAD

**Issue by itsmealves** [react-component/form#330]
Hi! When using the Form component, I get a lot of warnings in my console like this:

react-dom.development.js:12029 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Form(ProcedureForm)

**Comment by zhllucky** [comment]
did you solve it. and When I turn off debug mode，it will be Stuck

**Comment by zhllucky** [comment]
also I use react-native 0.60.5
