### ISSUE TITLE
No way to pass initial data into create form. 

### ISSUE THREAD

**Issue by GabrielCheung128** [react-component/form#334]
Hi, I am using AntD as our company's basic UI components. The function `Form.Create` does not provide a way for us to pass our original data object into the component. I used `mapPropsToFields` to achieve this but I have to store the data in parent state, otherwise, the data would be set to initial data when props change. I figure it out the reason is [here](https://github.com/react-component/form/blob/65013f9b69da09466caf31f23d2431ef3ecb8bac/src/createBaseForm.js#L90). I hope that mapPropsToField receives two arguments `nextProps` and `this.props` so that it could leave the user to determine whether the store should update the fields or not. 

``` javascript
      componentWillReceiveProps(nextProps) {
          if (mapPropsToFields) {
              const newFields = mapPropsToFields(nextProps, this.props);
              newFields && this.fieldsStore.updateFields(newFields);
          }
      }
```

Once the `componentWillReceiveProps` is called, I could tell that if the `data.id` or some sort has not changed, it would return false. Then the store would not update. With this no breaking changes update, I can use `mapPropsToFields` as initial data setter, which would be much easier for setting initial data.

**Comment by zombieJ** [comment]
`mapPropsToFields` is used for data control with store like redux. It's not the correct place to handle the initial value logic.

#### For redux
You need to put the initial value in store like:
```jsx
function todoApp(state = initialState, action) {
  // ...
  return state;
}
```

#### For non-store management
Just put initial value in `getFieldDecorator`:
```jsx
getFieldDecorator('name', {
  initialValue: 'someValue'
})
```
