### ISSUE TITLE
setFieldsValue后，getFieldsValue取不到

### ISSUE THREAD

**Issue by kasinooya** [react-component/form#38]
http://riddle.alibaba-inc.com/riddles/1f2aa50

**Comment by afc163** [comment]
。。。不要贴内网地址。

**Comment by kasinooya** [comment]
riddle好用呗 😄  赶紧解答下原理！

**Comment by kasinooya** [comment]
@benjycui 如上次群里讨论，项目是基于antd 1.x系列的，建议1.x也修复一下，thx~

**Comment by yiminghe** [comment]
不要这么用， getFieldProps 的才能 set/get

**Comment by kasinooya** [comment]
@yiminghe 所以这是设计问题？如果要往form里面设置没有表单域的值怎么办？

**Comment by benjycui** [comment]
事实上你那个例子是可以拿到这个值的：

![image](https://cloud.githubusercontent.com/assets/3580607/19427067/f28546ce-9473-11e6-891d-81fc88f88257.png)

**Comment by freeyiyi1993** [comment]
@yiminghe  getFieldProps可以获取setFieldsValue的值 但是提示**Warning: `getFieldProps` is not recommended, please use `getFieldDecorator` instead** 

在getFieldsValue不起作用的前提下 怎么获取表单域的值呢

**Comment by benjycui** [comment]
这个问题的确是存在。

@freeyiyi1993 需要 get  动态设置的值得目的是？

这个 feature 可能可以满足需求 https://github.com/ant-design/ant-design/issues/2965

**Comment by freeyiyi1993** [comment]
@benjycui 动态设置值 的目的是 给嵌套三层以上的自定义表单项赋值 链接里的issue和我遇到的是一个问题，但是似乎还没解决

**Comment by benjycui** [comment]
自定义表单项应该是会用到 `getFieldDecorator` 装饰 https://ant.design/components/form/#components-form-demo-customized-form-controls

所以直接 setFieldValue 是 OK 的才对。

Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by freeyiyi1993** [comment]
@benjycui 多谢 按照你给的提示 已经完美解决问题

**Comment by afc163** [comment]
或许需要加一个 warning，没绑定过的不允许 setFieldsValue 和 setFieldValue。

**Comment by duzhenyi** [comment]
子页面设置form的`this.form.setFieldValue({name:""})`
父页面this.$refs.form.getFieldsValue() 获取的时候 name为 undefined
