### ISSUE TITLE
feature: getFieldValue(field: String)

### ISSUE THREAD

**Issue by benjycui** [react-component/form#4]
当我想判断一个 field 的 `value` 是否为空串时，现在只能这样：

```js
if (!!getFieldsValue(['name']).name) {
  // do something
}
```

想增加一个 `getFieldValue` 函数，就可以用下面的方式访问：

```js
if (!!getFieldsValue('name')) {
  // do something
}
```

如果增加 `getFieldValue`，是否也需增加一个对应的 `setFieldValue(fieldName, value)`?

@yiminghe

**Comment by yiminghe** [comment]
getFieldsValue().name 就可以了，不增加单个

**Comment by benjycui** [comment]
原来已经有 `getFieldValue` 了，只是文档没有写。。

测试了一下这个方法 https://github.com/react-component/form/blob/master/src/createForm.jsx#L163

是可以这样使用的：

![image](https://cloud.githubusercontent.com/assets/3580607/12252194/0ba7aa92-b910-11e5-915b-46f888d5f01b.png)

这个方法不暴露的原因是？

**Comment by yiminghe** [comment]
ok, 文档写下吧

**Comment by benjycui** [comment]
https://github.com/react-component/form/commit/184d055de564b9d0177658dd92f9ca606e6e87bd

**Comment by zjxpcyc** [comment]
@benjycui 请问，你截图里面的 $r 是怎么得到的？ 你的截图是直接 console 的截图吗？

**Comment by afc163** [comment]
是否需要搞一个 `setFieldValue`？
