### ISSUE TITLE
为什么 dependencies  里面有 babel-runtime

### ISSUE THREAD

**Issue by nimojs** [react-component/form#41]
https://github.com/react-component/form/blob/616ddd309d9ede65c652c3a158f7e1b08b9e8d1e/package.json#L62

**Comment by benjycui** [comment]
既然你已经决定了要研究实现，为了么连 Google 一下都不愿意？ https://www.google.co.id/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=babel-runtime

**Comment by nimojs** [comment]
怪我表述不清楚，我知道 babel 是什么。
因为我在 git 搜索 babel-runtime  https://github.com/react-component/form/search?utf8=%E2%9C%93&q=babel-runtime 在 src 没有找到babel-runtime 的引用。

我猜测 babel-runtime 是给构建工具用的 所以想弄明白为什么不在 devDependencies 在 dependencies
