### ISSUE TITLE
执行页面查询报如下的错：ETIMEDOUT 127.0.0.1:8000

### ISSUE THREAD

**Issue by xuhongxin** [react-component/form#422]
![image](https://user-images.githubusercontent.com/1044109/88295135-9a0e3200-cd2f-11ea-8ce5-885959dbc689.png)

按照说明执行npm start之后，我想看对应页面的执行效果，点击对应的html页面报错：

Error: connect ETIMEDOUT 127.0.0.1:8000
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)

**Comment by 07akioni** [comment]
这个库有点老了，如果你不是在维护老项目的话，感觉你应该看看新的 field-form

**Comment by xuhongxin** [comment]
> 这个库有点老了，如果你不是在维护老项目的话，感觉你应该看看新的 field-form

果然，切到field-form就可以了；非常感谢。
