### ISSUE TITLE
[Question] FormInstance method

### ISSUE THREAD

**Issue by seonghyeonkimm** [react-component/form#432]
1. Is there a way to get all values from fieldstore? 
2. Is there a way to replace object value with new object?
  - For example, I set FieldsValue as `{ selected: { '1': true, '2': true } }`
  - After that, I want to replace values with `{ selected: { '1': true } }` totally.

When I searched, I could not find out the way to achieve things above.
Somebody can comment on this?

**Comment by yoyo837** [comment]
1.  https://github.com/react-component/form#getfieldsvaluefieldnames-string
2. You can't do that, you can only get this:

 before:

 ` { selected: { '1': true, '2': true } }`

after:
 ` { selected: { '1': true, '2': null } }` or  ` { selected: { '1': true, '2': undefined } }` Unless discarded when re-rendering.

**Comment by seonghyeonkimm** [comment]
Thanks for your kind reply. I will find out the other way to achieve my goal by the way. @yoyo837
