### ISSUE TITLE
warning 

### ISSUE THREAD

**Issue by vince-fly** [react-component/form#45]
Form is changing an uncontrolled input of type undefined to be controlled. Input elements should not switch from uncontrolled to controlled(or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components

**Comment by benjycui** [comment]
Try to set [`initialValue`](https://github.com/react-component/form#optioninitialvalue)

**Comment by deot** [comment]
@benjycui good
