### ISSUE TITLE
Using normalize but still get unformatted data in the onSubmit callback

### ISSUE THREAD

**Issue by spoldman** [react-component/form#49]
The problem is that the value of the input field is 1000 it then gets normalized into 1,000 which is all good but on onSubmit the value is 1.000 but I want it to be unformatted.

I tried using normalize and getValueFromEvent together with no success. Maybe this is not possible and has to be done outside the scope of rc-form.

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/NdQdBw?editors=0011

**Comment by paranoidjk** [comment]
close for no response.
