### ISSUE TITLE
feature: option.validateTrigger 支持数组

### ISSUE THREAD

**Issue by benjycui** [react-component/form#5]
[`option.validateTrigger`](https://github.com/react-component/form#optionvalidatetrigger) 现在的设计只支持一个 trigger，如果我有一个 `input[email][required]` 希望：

1. `onBlur` 的时候进行校验，以确保用户有输入
2. `onChange` 的时候进行校验，以确保格式正确

现在的 API 好像不行。

**Comment by yiminghe** [comment]
```js
{
  validate:[{
    trigger: '',
    rules:[]
  }]
}
```

**Comment by benjycui** [comment]
其实我觉得 `validateTrigger: ['onBlur', 'onChange']` 或者 `validateTrigger: 'onBlur onChange'` 这样比较容易实现也比较容易使用。。

**Comment by yiminghe** [comment]
? 应该是不同 trigger 不同 rules
