### ISSUE TITLE
validateFields 会触发 form 的 onFieldsChange 回调

### ISSUE THREAD

**Issue by AmBeta** [react-component/form#52]
使用如下的方式给 form 绑定上 onChange 回调后，调用 validateFields 或者validateFieldsAndScroll 时会触发该回调，这样会导致需要验证的域在改变的时候会触发两次该回调。

```
Form.create({
  onFieldsChange(props, changedFields) {
    props.onChange(changedFields);
  }
})(BaseForm);
```

**Comment by benjycui** [comment]
It's by designed.

We need `onValuesChange` to simplify this use case.

**Comment by AmBeta** [comment]
这个解决方法不错。

在目前的版本上，我是手动给每个 component 绑定上了 onChange 。
