### ISSUE TITLE
动态 form 中 name 不变时,  getFieldProps 先于 saveRef 触发, 导致 fieldMeta 为 undefined, 引发报错

### ISSUE THREAD

**Issue by sandwich99** [react-component/form#53]
错误:

![image](https://cloud.githubusercontent.com/assets/1179783/21603405/0b833482-d1d8-11e6-895a-8b7ce09a7bc8.png)

Form 由于使用了高阶组件,  先调用了 getFieldProps , 包含初始化 fieldMeta 

```javascript
fieldMeta = fieldsMeta[name] = fieldsMeta[name] || {};
```

rc-form 重载了 ref

```javascript
inputProps.ref = this.getCacheBind(name, `${name}__ref`, this.saveRef);
```
该方法会在 component unmount 时调用

![image](https://cloud.githubusercontent.com/assets/1179783/21603191/418a3f5a-d1d6-11e6-8fc3-729ee5a0d052.png)

saveRef 清理了 meta state
```javascript
      saveRef(name, _, component) {
        if (!component) {
          // after destroy, delete data
          delete this.fieldsMeta[name];
          delete this.fields[name];
          delete this.instances[name];
          delete this.cachedBind[name];
          return;
        }
        const fieldMeta = this.getFieldMeta(name); // 第二次调用时 由于 fieldMeta 为空, 所以并不会执行 ref(component)
        if (fieldMeta) {
          const ref = fieldMeta.ref;
          if (ref) {
            if (typeof ref === 'string') {
              throw new Error(`can not set ref string for ${name}`);
            }
            ref(component);
          }
        }
        this.instances[name] = component;
      },
```

在 react attachRef时, saveRef 会再次被调用, 但此时 fieldMeta 已经在 unmount 时被删除了
![image](https://cloud.githubusercontent.com/assets/1179783/21603344/8a89ae88-d1d7-11e6-95bb-ee2c4fae43d6.png)

所以此时 ref(component) 不会被触发, 导致报错

![image](https://cloud.githubusercontent.com/assets/1179783/21603395/e9c342ba-d1d7-11e6-9b56-a27f5dde53cb.png)

**Comment by benjycui** [comment]
此 issue 关闭，跟进 antd 中的那个即可。

**Comment by kala888** [comment]
类似问题，在使用react-weui的时候，使用weui的Input会报同样的错
