### ISSUE TITLE
lose value with nested fields :( 

### ISSUE THREAD

**Issue by plandem** [react-component/form#59]
https://github.com/ant-design/ant-design/issues/4711

**Comment by plandem** [comment]
looks like in case of redux, i HAVE to flat the object.

this will not work
```
{
 name: { value: "aaa" },
 config: { nested: { value: "bbb" }}
}
```

this WILL work:
```
{
 name: { value: "aaa" },
 config.nested: { value: "bbb" }
}
```

There is no any information about flatting object. You need to fix documentation or bug (if it's supposed behavior).

**Comment by benjycui** [comment]
Just trace issue in ant-design.

**Comment by lifeneedspassion** [comment]
nested fields are bullshit
