### ISSUE TITLE
【建议】提供动态设置validte相关api

### ISSUE THREAD

**Issue by swxy** [react-component/form#64]
在用`form`表单时，经常需要封装一些自定义组件，相对应的检验规则希望能在这些组件中动态设置，而不是统一在使用`getFieldDecorator`时传入。

**Comment by benjycui** [comment]
如果是和自定义表单组件一起使用的问题，参见 https://ant.design/components/form-cn/#components-form-demo-customized-form-controls

如果是要在运行时动态修改一个表单域的校验规则，现在暂不支持，后面空了再搞吧。。

**Comment by swxy** [comment]
我其实想要的就是能在运行时动态修改一个表单域的校验规则。。。现在只能在自定义的组件中调用`getFieldProps`来覆盖检验规则，期待能尽快加上，感谢。

**Comment by benjycui** [comment]
https://github.com/ant-design/ant-design/pull/6035
