### ISSUE TITLE
能不能更新一下 file input 的例子为使用getFieldDecorator的?

### ISSUE THREAD

**Issue by blog-lyn** [react-component/form#66]
我按照以下两个例子,试图把file input的 formData 放在redux中,但是出现了报错.
实在不知道使用getFieldDecorator正确的写法是怎么样的?
能否更新一下getFieldDecorator的那个例子?
谢谢

http://react-component.github.io/form/examples/redux.html
http://react-component.github.io/form/examples/file-input.html

```
getValueFromFileEvent({ target }) {
      return  {target};
}
...

{getFieldDecorator('contentFile', {
    getValueFromEvent: this.getValueFromFileEvent.bind(this),
})(<input   type="file" />)}

...

export default connect(mapStoreToProps, mapDispatchToProps)(Form.create({
    mapPropsToFields(props) {
        return {
            contentFile: props.formData.contentFile,
        };
    },
    onFieldsChange(props, fields) {
        props.setTemplateForm(fields);
    },
})(AddTemplate));
```
报错:
 

> Warning: AddTemplate is changing an uncontrolled input of type file to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components
> 
> Uncaught DOMException: Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string.
>

**Comment by blog-lyn** [comment]
现在暂时是这么实现的, 但是感觉这肯定不是best practice

```
{getFieldDecorator('contentFile', {      
    'rules': [{ validator: this.checkFileContent.bind(this) }]
})(<Input ref={input => { this.contentFileNode = input; }}  type="file" />)}

//当未选择时上传文件时  new一个空的
getEmptyBolb(){
        var blob = new Blob([''], {type : 'application/octet-stream'});
        return new File([blob], '');
}
// 下面是 handleOk时 获取值
const contentFile=this.contentFileNode.refs.input.files&&this.contentFileNode.refs.input.files.length > 0 ? this.contentFileNode.refs.input.files[0] : this.getEmptyBolb();
                const formData = new FormData();
                formData.append('contentFile', contentFile);
```

**Comment by benjycui** [comment]
getFieldDecorator 就是基于 getFieldProps 实现的，没什么特别。

另外其实不是很建议把 rc-form 的 state 同步到 redux 中，技术上虽然可行，但是性能不好，而且也没有必要。

大多数情况下，form 的数据与页面其他部分都是隔离的吧，所以同步到 redux 的意义不大。
