### ISSUE TITLE
mapPropsToFields 不能给 nested-field 赋初始值...

### ISSUE THREAD

**Issue by szrenwei** [react-component/form#72]
按照官网的 nested-field 例子，将 setFieldsValue 赋值改变成 mapPropsToFields，nested-field 不能得到初始值，其他 field 能正常赋值。

**Comment by annalihan** [comment]
同遇到这个问题，求解

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/NdQdBw?editors=0011

**Comment by yeluolei** [comment]
同遇到这个问题

**Comment by JuneChiu** [comment]
同样遇到这个问题，希望可以有答复 @benjycui

**Comment by MathiasGilson** [comment]
Yes I get the same issue, according to rc-form doc this should work, any chance that the issue is coming from the required field "value" inside a mapPropsToFields field ?

In this [rc-form example](http://react-component.github.io/form/examples/nested-field.html) you can see that they set nested value without problem but they don't use the "value" field : 
they do 
`
this.props.form.setFieldsValue({
      emails: [
        {
            email: "test@test.test"
        }
      ]`
and in antd it's required to do
`
this.props.form.setFieldsValue({
      emails: [
        {
           email: {
                value: "test@test.test"
           }
        }
      ]
`

I think that might be causing the problem

**Comment by MathiasGilson** [comment]
This [codepen](https://codepen.io/MathiasGilson/pen/jLapPz?editors=0010) shows you what is expected to work and does not

**Comment by benjycui** [comment]
Try rc-form@2.0.0, and changelog https://github.com/react-component/form/blob/master/HISTORY.md#200--2017-11-07

If you meet any issue, feel free to file an issue, and I will try to fix it asap.

**Comment by badaljain** [comment]
Hi, How can we set nested dynamic fields? I have an array of inputs and based on that the text boxes are to be created. please give me a pointer!

**Comment by chillyistkult** [comment]
I think a lot of people are facing the exact same issue and so far there is no solution provided other then nasty hacks and workarounds. Is there a recommend way to sync a redux store with rc-form without having to write thousands of lines of boilerplate code?

Sure you could start with mapPropsToFields and even iterate over the keys of your redux state to produce the intialState of the form like so

```
@Form.create({
  mapPropsToFields: props => {
    const { data } = props.offer
    return Object.keys(props.offer.data).reduce((acc, cv) => {
      return {
        ...acc,
        [cv] : Form.createFormField({
          value: data[cv],
        }),
      }
    }, {})
  },
})
```

but this will not work for nested fields and to be honest this alone is just awkward and feels wrong. It looks like the main problem here is that `value` field is required by rc-forms and the introduction of `Form.createFormField`. For that reason you will have a hard time to sync form state with your data model.

**Comment by vincro** [comment]
@chillyistkult as clunky as the above is, its possible to get the form setup and running with pre-populated date.  What seems harder is getting the array out of the form with updates, as the field value currently comes out as an object:

`{
    0: 'item 1',
    1: 'item 2',
    "": ['original', 'array', 'values']
}`

seems like an issue with rc-form not being able to handle the return values for arrays.
