### ISSUE TITLE
what is magic about getFieldDecorator and initialValue?

### ISSUE THREAD

**Issue by plandem** [react-component/form#73]
I have 2 custom components: 

(1) is working - I don't have to provide **initialValue**
component with **valuePropName** as string
```jsx
{getFieldDecorator('background', { valuePropName: 'color'})(
	<ColorPicker/>
)}
```

(2) is NOT working - I HAVE to provide **initialValue**
component with **valuePropName** as array
```jsx
{getFieldDecorator('range', { valuePropName: 'limit', initialValue: get(info, 'range')})(
	<RangeInput/>
)}
```

**Comment by paranoidjk** [comment]
getFieldDecorator add `onChange`, `value` to your component, which make it under controlled.

I do not know where `RangeInput` come from.

and you should provide your detail error info.

**Comment by plandem** [comment]
not matter what is **RangeInput**. My issue was that if my component works with array, then I have to provide initialValue manually.

at antd we have CheckBox.Group and value is array of strings:
https://ant.design/components/checkbox/

**getFieldDecorator** can't get initialValue by self, I have to provide it.

**Comment by paranoidjk** [comment]
sorry, I still haven't understand your problem,  please describle it more clearly, a reproducible demo is better.

**Comment by plandem** [comment]
behavior is not same for Component that works with arrays and Component that works with simple values:

must be
```jsx
<Form.Item>
       {getFieldDecorator('title'})(
              <Input/>
       )}
</Form.Item>

<Form.Item>
       {getFieldDecorator('user_options'})(
              <Checkbox.Group options={all_options}/>
       )}
</Form.Item>
```

right now:
```jsx
<Form.Item>
       {getFieldDecorator('title'})(
              <Input/>
       )}
</Form.Item>

<Form.Item>
       {getFieldDecorator('user_options', { initialValue: info.user_options) })(
              <Checkbox.Group options={all_options}/>
       )}
</Form.Item>
```
as you see I don't need to provide **initialValue** for **Input**, but I HAVE to provide initialValue for **Checkbox.Group**.

**Comment by paranoidjk** [comment]
> as you see I don't need to provide initialValue for Input, but I HAVE to provide initialValue for Checkbox.Group.

`initialValue` is just like `defaultValue`, it used for [controlled-components](https://facebook.github.io/react/docs/forms.html#controlled-components), If your comopnent do not need defaultValue, i do not see any reason that you must provide it 

what do you mean **I HAVE to provide initialValue for Checkbox.Group.** ? what if you don't provide it , is there any console error ? see https://ant.design/components/checkbox/#Checkbox-Group

**Comment by plandem** [comment]
I don't how to describe it more. Have you tried to use **getFieldDecorator** for **Checkbox.Group**?

Here is demo with what I was talking about:
http://codepen.io/anon/pen/VbpWNj?editors=0010

As you can see, **Checkbox.Group** doesn't get **initialValue** by self

**Comment by paranoidjk** [comment]
If you provide your codepen demo at the begining, we do not need to waste so many times to ask and answer.

https://github.com/ant-design/ant-design/issues/5957
