### ISSUE TITLE
0.17升级到1.3会有兼容问题么？

### ISSUE THREAD

**Issue by sydeEvans** [react-component/form#75]

**Comment by paranoidjk** [comment]
主要应该是对着check 0.13 ~ 1.0 的几次changelog看

https://github.com/react-component/form/blob/master/HISTORY.md#0130--2016-02-14

**Comment by benjycui** [comment]
这个我也说不清了。。 rc 这一层都没有整理过更新文档。

只能靠回归了。。

如果是使用 antd，可以参考对应的更新文档。
