### ISSUE TITLE
validateFields 不会触发 通过validator自定义的校验方法，is that expected?

### ISSUE THREAD

**Issue by Peiren** [react-component/form#78]

**Comment by Peiren** [comment]
抱歉，使用问题

**Comment by sanshuiwang** [comment]
我靠，这一句话惊醒了我。我每个item都写了validator
走了半天的validateFields就是进不去，尴尬，，，

**Comment by sanshuiwang** [comment]
后来发现validator在通过很多if判断非法后，忘记执行callback()这样啊


![image](https://user-images.githubusercontent.com/20984566/55497298-a6bad280-5673-11e9-89cd-1902ba464ee1.png)
