### ISSUE TITLE
getFieldError()表单初始化和验证通过返回值能否区分一下

### ISSUE THREAD

**Issue by wutianmei** [react-component/form#80]
一进入表单页面时什么都没有输入，调用 getFieldError('name')返回 undefined，当name字段较验通过时再次再用getFieldError('name')返回的仍是 undefined，这两种情况的返回值能否区分一下，以便我们来做其他处理，比如 submit按钮禁用等操作!

**Comment by paranoidjk** [comment]
按钮禁用不应该通过这个状态来区分，getFieldError 是标志是否有表单校验错误

**Comment by benjycui** [comment]
Use: https://github.com/react-component/form#isfieldtouchedname-string-bool

See: https://ant.design/components/form/#components-form-demo-horizontal-login

**Comment by wutianmei** [comment]
@paranoidjk @benjycui 多谢
