### ISSUE TITLE
isFieldsTouched not respecting nested property names

### ISSUE THREAD

**Issue by bkniffler** [react-component/form#83]
Hey, 
isFieldsTouched returns all fields that changed but will not make a difference between top level fields or nested ones. I'd expect to have the dotted property name (`user.firstName`), that I also use on the getFieldDecorator to bind to my input.

**Comment by benjycui** [comment]
I don't understand. According to me, it works fine.

Could you provide more information?

**Comment by bkniffler** [comment]
Sorry, my bad. Seems like I did it wrong.
