### ISSUE TITLE
Nested Fields with Redux

### ISSUE THREAD

**Issue by mitchelldemler** [react-component/form#90]
I am currently using onFieldsChange and mapPropsToFields to connect my form to Redux.

I'm running into issues when managing repeatable rows of inputs (nested fields). At the moment I am using the example in the AntD docs, and putting a key in the field name. eg: fields-fieldName-123.

I would like to use the nested field syntax of: fields[123].fieldName instead. 

My formReducer currently puts the changedFields straight into my Redux store to mimic the rc-form state.
```
const FormReducer = (state = InitialAppState.formState, action) => {
    switch (action.type) {
        case types.FORM_UPDATE:
            return {
                ...state,
                ...action.changedFields,
            };
        default:
            return state;
    }
};
```

Any ideas on how to improve this? At the moment in my project, it feels like there is two sources of truth - the rc-form state, and the redux store. I would like these to be the same.

**Comment by yeluolei** [comment]
same problem here, please provide example for nest form and mapPropsToFields

**Comment by MathiasGilson** [comment]
You can refer to this [example](http://react-component.github.io/form/examples/nested-field.html)
but it doesn't appear to work well with antd, see this [issue](https://github.com/ant-design/ant-design/issues/7228)

**Comment by benjycui** [comment]
Try rc-form@2.0.0, and changelog https://github.com/react-component/form/blob/master/HISTORY.md#200--2017-11-07

If you meet any issue, feel free to file an issue, and I will try to fix it asap.
