### ISSUE TITLE
调用form.validateFields方法会改变WrappedComponent的props.form，从而触发componentWillReceiveProps

### ISSUE THREAD

**Issue by ufohjl** [react-component/form#91]
但是实际上form是一堆方法组成的object，只是重新生成了一个form，里面的方法并没有任何变化。
```
componentWillReceiveProps(nextProps) {
    console.log(nextProps.form === this.props.form) // false

    for (let key of Object.keys(this.props.form)) {
      console.log(this.props.form[key] === nextProps.form[key]) // ALL true
    }
 }
```
这里探讨一下是否有必要每次props中都返回一个新的form实例？

个人观点：直接将form缓存起来，指向同一个实例，避免每次调用HOC的render都生成新的form实例从而触发WrappedComponent的componentWillReceiveProps

**Comment by ufohjl** [comment]
[https://github.com/ant-design/ant-design/issues/2985](url)
也可以一并解决这个问题

在componentWillReceiveProps生命周期方法里调用setFieldsValue应该也是比较合理的需求，不应该因此而产生死循环

**Comment by benjycui** [comment]
其实 `setFieldsValue` 导致 re-render 并不是因为 form 的引用不一致，而是因为内部使用了 `.forceUpdate()`

**Comment by benjycui** [comment]
> 直接将form缓存起来，指向同一个实例

技术上可以缓存，但是这个不缓存成本也不高吧。

对于缓存，个人观点是如无必要不要增加，之前就有几个组件是缓存没实现好导致了诡异的 bug。
