### ISSUE TITLE
Nested rules errors are omitted in getFieldsError

### ISSUE THREAD

**Issue by queimadus** [react-component/form#93]
Lets take the following definition of decorator for an item whose value is always the same array:
```jsx
getFieldDecorator("arrayItem" {
  initialValue: ["a", 1, "c"],
  rules: [{type: "array", defaultField: {type: "number" }]
})(<div />)
```

Calling `validateFields` will return an correct `error` like:
```json
{
  "arrayItem": [{
      "errors": [{
        "field": "arrayItem.0",
        "message": "arrayItem.0 is not a number"
      }]
    }, {
      "errors": [{
        "field": "arrayItem.2",
        "message": "arrayItem.2 is not a number"
      }]
  }]
}
```

Calling `getFieldError("arrayItem")` or `getFieldError("arrayItem.0")` will return nothing. 
The generated, omitted, errors are found in `"arrayItem.0"` and `"arrayItem.2"`.

This is because after we correctly obtain all errors, we only iterate over the ids that have rules defined in [createBaseForm:376](https://github.com/react-component/form/blob/master/src/createBaseForm.js#L375).

**Comment by queimadus** [comment]
My use case is that I have a widget that returns an array value.

I'd like to apply validations to each element individually in order to show the error only in the affected array element, instead of the widget as a whole. 

It's not practical to inject a `getFieldDecorator("arrayItem[${idx}]")` for each array element although that might work.

**Comment by benjycui** [comment]
Yep, because of the fucking nested field feature... Need a demo, thanks.

Please provide a re-producible demo: http://codepen.io/benjycui/pen/NdQdBw?editors=0011

**Comment by queimadus** [comment]
https://codepen.io/anon/pen/xLzgea?editors=0011

In the example, the `arrayItem` errors appear in the `validateErrors` but can't be accessed with `getFieldError`. As a working example I've added a "simple" error which appears in both methods. 

On a sidenote, you should put that codepen link in the README.md, I would have created reproducible example straight away but I had trouble getting rc-form to work in codepen.

**Comment by queimadus** [comment]
Can you confirm the bug with the provided demo?

**Comment by benjycui** [comment]
`arrayItem.0` means a field with name `arrayItem.0`, such as  `getFieldProps('arrayItem.0')`, not the first item of `arrayItem`.

**Comment by queimadus** [comment]
How should one extract the individual validation errors from a rule with type `array` then?

**Comment by Miced** [comment]
Is there any example on using the nested fields validation feature of [async-validator](https://github.com/yiminghe/async-validator)? This seems to be asked alot and no example is provided.
