### ISSUE TITLE
一个关于 readme 的思考

### ISSUE THREAD

**Issue by zjxpcyc** [react-component/form#96]
今天看 readme 的时候突然想到一个问题。
为什么，rc 的 readme 全部是英文的？是阿里的内部要求吗？
或者想要走出国门的原因？
要走出国门，难道中文就可以没有吗？ rc 的用户 90% 是外国友人？

我印象里面，之前高晓松说过一句话，说他年轻的时候，大家都给自己起一个英文名，什么 jack li, （这里我是想尽量引用高晓松的原话，没有任何针对或者讽刺马老板 jack ma 的意思）之类的, 以为这样就能很快融入外国的生活圈。

但是实际上这样做有没有用，或者说起了多大的作用，大家心底自己都有一个答案。

我上面说了这么多，不是说我是键盘侠，我是喷子，只是我的一个念头闪过。

个人感觉，中文 readme 也是不可或缺的。

**Comment by afc163** [comment]
您好，大概原因是没有足够的精力维护两份文档。欢迎贡献。
